export const dataFromBackend = [
  {
    url_1: 'https://dezwartdranken.nl/product/lenotti-capomastro/',
    name: 'Lenotti Capomastro',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/62510_lenotti_capomastro_1.jpg',
    price: 9.95,
    wine_type: 'Red Wine',
    grapes: 'Corvina, Rondinella, Molinara, Rebo',
    region: 'Italy / Veneto',
    wine_style: 'Northern Italy Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/salentein-barrel-selection-merlot/',
    name: 'Salentein Barrel Selection Merlot',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/salentein-barrel-merlot.jpg',
    price: 14.95,
    wine_type: 'Red Wine',
    grapes: 'Merlot',
    region: 'Argentina / Tunuyán',
    wine_style: 'Argentinian Merlot',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/pasqua-passimento-rosso/',
    name: 'Pasqua Passimento Rosso',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/passimento_rosso.jpg',
    price: 11.75,
    wine_type: 'Red Wine',
    grapes: 'Glera, Corvina',
    region: 'Italy / Veneto',
    wine_style: 'Northern Italy Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/degras-reserva-merlot/',
    name: 'Degras Reserva Merlot',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/de-gras-merlot-reserva-1431633-s507_p.jpg',
    price: 9.95,
    wine_type: 'Red Wine',
    grapes: 'Merlot',
    region: 'Chile / Colchagua Valley',
    wine_style: 'Chilean Merlot',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/doos-salentein-barrel-selection-merlot/',
    name: 'Doos Salentein Barrel Selection Merlot',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/salentein-barrel-merlot.jpg',
    price: 89.7,
    wine_type: 'Red Wine',
    grapes: 'Merlot',
    region: 'Argentina / Tunuyán',
    wine_style: 'Argentinian Merlot',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/oxford-landing-estates-merlot/',
    name: 'Oxford Landing Estates Merlot',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/oxford-landing-merlot.jpg',
    price: 7.95,
    wine_type: 'Red Wine',
    grapes: 'Merlot',
    region: 'Australia / South Australia',
    wine_style: 'Australian Merlot',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/corterosso/',
    name: 'Corterosso',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/corterosso_1.jpg',
    price: 7.95,
    wine_type: 'Red Wine',
    grapes: 'Sangiovese',
    region: 'Italy / Emilia-Romagna / Emilia / Rubicone',
    wine_style: 'Northern Italy Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/degras-estate-merlot/',
    name: 'Degras Estate Merlot',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/degras-estate-merlot-2018-1.jpg',
    price: 6.95,
    wine_type: 'Red Wine',
    grapes: 'Cabernet Sauvignon, Merlot',
    region: 'Chile / Central Valley',
    wine_style: 'Chilean Merlot',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/errazuriz-merlot-estate/',
    name: 'Errazuriz Merlot Estate',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Errazuriz-Estate-Merlot.jpg',
    price: 9.95,
    wine_type: 'Red Wine',
    grapes: 'Merlot, Carménère',
    region: 'Chile / Curico Valley',
    wine_style: 'Chilean Merlot',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/baglio-al-sole-primitivo/',
    name: 'Baglio Al Sole Primitivo',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/baglio-al-sole-primitivo.jpg',
    price: 7.95,
    wine_type: 'Red Wine',
    grapes: 'Primitivo',
    region: 'Italy / Salento',
    wine_style: 'Southern Italy Primitivo',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/epicuro-primitivo-puglia/',
    name: 'Epicuro Primitivo Puglia',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Epicuro-Primitivo.jpg',
    price: 8.95,
    wine_type: 'Red Wine',
    grapes: 'Primitivo',
    region: 'Italy / Puglia',
    wine_style: 'Southern Italy Primitivo',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/poggio-le-volpi-tator-primitivo/',
    name: 'Poggio Le Volpi Tator Primitivo',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/edf1e1cd583c54290bbf35ae21c6f1eca5e43c5b.jpg',
    price: 18.95,
    wine_type: 'Red Wine',
    grapes: 'Primitivo',
    region: 'Italy / Salento',
    wine_style: 'Southern Italy Primitivo',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/sedosa-tempranillo-syrah/',
    name: 'Sedosa Tempranillo - Syrah',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Sedosa-Tempranillo-Shiraz-450x450-1.jpg',
    price: 6.75,
    wine_type: 'Red Wine',
    grapes: 'Shiraz/Syrah, Tempranillo',
    region: 'Spain / Castilla',
    wine_style: 'Spanish Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/pierre-jean-cabernet-merlot-doosprijs/',
    name: 'Pierre Jean Cabernet - Merlot (Doosprijs)',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/pierre-jean-doos.jpg',
    price: 33,
    wine_type: 'Red Wine',
    grapes: 'Cabernet Sauvignon, Merlot',
    region: 'France / Aude',
    wine_style: 'Languedoc-Roussillon Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/finca-museum-real-reserva-cigales/',
    name: 'Finca Museum Real Reserva Cigales',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/museum_real.jpg',
    price: 19.5,
    wine_type: 'Red Wine',
    grapes: 'Tempranillo',
    region: 'Spain / Castilla y León / Cigales',
    wine_style: 'Spanish Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/ramon-bilbao-crianza/',
    name: 'Ramon Bilbao Crianza',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/ramon-bilbao-crianza-1222978.png',
    price: 12.95,
    wine_type: 'Red Wine',
    grapes: 'Tempranillo',
    region: 'Spain / Rioja',
    wine_style: 'Spanish Tempranillo',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/laurent-miquel-pere-et-fils-syrah-grenache/',
    name: 'Laurent Miquel Père et Fils Syrah - Grenache',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/laurent-miquel-pere-et-fils-syrah-grenache-2018-ig.jpg',
    price: 7.95,
    wine_type: 'Red Wine',
    grapes: 'Shiraz/Syrah, Grenache',
    region: "France / Pays d'Oc",
    wine_style: 'Languedoc-Roussillon Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/manoir-grignon-cabernet-syrah/',
    name: 'Manoir Grignon Cabernet Syrah',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/manoir_grignon_cab_syrah15.jpg',
    price: 7.95,
    wine_type: 'Red Wine',
    grapes: 'Shiraz/Syrah, Cabernet Sauvignon',
    region: "France / Pays d'Oc",
    wine_style: 'Languedoc-Roussillon Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/marques-de-riscal-rioja-reserva/',
    name: 'Marqués de Riscal Rioja Reserva',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/marques-de-riscal-reserva-1356417.jpg',
    price: 18.5,
    wine_type: 'Red Wine',
    grapes: 'Tempranillo',
    region: 'Spain / Rioja',
    wine_style: 'Spanish Rioja Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/ramon-bilbao-edicion-limitada/',
    name: 'Ramon Bilbao Edición Limitada',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Ramon-Bilbao-Edicion-Limitada-Rioja.jpg',
    price: 16.5,
    wine_type: 'Red Wine',
    grapes: 'Tempranillo',
    region: 'Spain / Rioja',
    wine_style: 'Spanish Rioja Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/ramon-bilbao-reserva/',
    name: 'Ramon Bilbao Reserva',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/RAMON-BILBAO-RESERVA.jpg',
    price: 17.95,
    wine_type: 'Red Wine',
    grapes: 'Tempranillo',
    region: 'Spain / Rioja',
    wine_style: 'Spanish Rioja Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/pierre-jean-cabernet-merlot/',
    name: 'Pierre Jean Cabernet - Merlot',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/download-1.jpg',
    price: 5.5,
    wine_type: 'Red Wine',
    grapes: 'Cabernet Sauvignon, Merlot',
    region: 'France / Aude',
    wine_style: 'Languedoc-Roussillon Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/ramon-bilbao-gran-reserva/',
    name: 'Ramon Bilbao Gran Reserva',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/0afbeelding0412370_12.jpg',
    price: 29.95,
    wine_type: 'Red Wine',
    grapes: 'Tempranillo',
    region: 'Spain / Rioja',
    wine_style: 'Spanish Rioja Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/salentein-barrel-selection-jeroboam-30-liter/',
    name: 'Salentein Barrel Selection Jeroboam (3,0 liter)',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/300cl-salentein-barrel-selection-malbec-2017-valle.jpg',
    price: 67.95,
    wine_type: 'Red Wine',
    grapes: 'Malbec',
    region: 'Argentina / Mendoza',
    wine_style: 'Argentinian Bordeaux Blend',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/artimone-vino-rosso-non-vintage/',
    name: 'Artimone Vino Rosso Non Vintage',
    image: 'https://dezwartdranken.nl/wp-content/uploads/2020/03/01042.jpg',
    price: 8.95,
    wine_type: 'Red Wine',
    grapes: 'Negroamaro, Primitivo, Sangiovese',
    region: 'Italy / Sicily',
    wine_style: 'Southern Italy Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/delaire-graff-estate-banghoek-reserve-chardonnay/',
    name: 'Delaire Graff Estate Banghoek Reserve Chardonnay',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Tekengebied-1-80-600x600-1.png',
    price: 22.95,
    wine_type: 'Red Wine',
    grapes: 'Merlot',
    region: 'South Africa / Stellenbosch',
    wine_style: 'South African Merlot',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/salentein-barrel-selection-cabernet-sauvignon/',
    name: 'Salentein Barrel Selection Cabernet Sauvignon',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/salentein-barrel-cabernet-sauvignon-800x800-1.jpg',
    price: 14.95,
    wine_type: 'Red Wine',
    grapes: 'Cabernet Sauvignon',
    region: 'Argentina / Tunuyán',
    wine_style: 'Argentinian Cabernet Sauvignon',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/doos-salentein-barrel-selection-cabernet-sauvignon/',
    name: 'Doos Salentein Barrel Selection Cabernet Sauvignon',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/salentein-barrel-cabernet-sauvignon-800x800-1.jpg',
    price: 89.7,
    wine_type: 'Red Wine',
    grapes: 'Cabernet Sauvignon',
    region: 'Argentina / Rio Negro',
    wine_style: 'Argentinian Cabernet Sauvignon',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/radford-dale-frankenstein-pinotage/',
    name: 'Radford Dale Frankenstein Pinotage',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/radford-dale-frankenstein-pinotage-2015-stellenbosch-sydafrika-32.jpg',
    price: 34.95,
    wine_type: 'Red Wine',
    grapes: 'Pinotage',
    region: 'South Africa / Stellenbosch',
    wine_style: 'South African Pinotage',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/doos-salentein-barrel-selection-malbec/',
    name: 'Doos Salentein Barrel Selection Malbec',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/salentein-barrel-selection-malbec-2018-valle-de-uc.jpg',
    price: 89.7,
    wine_type: 'Red Wine',
    grapes: 'Malbec',
    region: 'Argentina / Patagonia',
    wine_style: 'Argentinian Malbec',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/boschendal-1685-merlot/',
    name: 'Boschendal 1685 Merlot',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/silo-6001660004623-front-332222_400Wx400H.jpg',
    price: 14.95,
    wine_type: 'Red Wine',
    grapes: 'Merlot',
    region: 'South Africa / Coastal Region',
    wine_style: 'South African Merlot',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/monta-tempranillo-petit-verdot/',
    name: 'Monta Tempranillo & Petit Verdot',
    image: 'https://dezwartdranken.nl/wp-content/uploads/2020/03/954098525.jpg',
    price: 6.95,
    wine_type: 'Red Wine',
    grapes: 'Tempranillo, Petit Verdot',
    region: 'Spain / Castilla',
    wine_style: 'Spanish Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/simonsig-pinotage/',
    name: 'Simonsig Pinotage',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/simonsigpinotage2_800x.jpg',
    price: 13.5,
    wine_type: 'Red Wine',
    grapes: 'Pinotage',
    region: 'South Africa / Stellenbosch',
    wine_style: 'South African Pinotage',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/degras-reserva-cabernet-sauvignon/',
    name: 'Degras Reserva Cabernet Sauvignon',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/de-gras-cabernet-sauvignon-reserva-2017-1x-75cl_550.jpg',
    price: 9.95,
    wine_type: 'Red Wine',
    grapes: 'Cabernet Sauvignon',
    region: 'Chile / Central Valley',
    wine_style: 'Chilean Cabernet Sauvignon',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/errazuriz-carmenere-estate/',
    name: 'Errazuriz Carmenere Estate',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/errazuriz-estate-carmenere-reserva-2018-aconcagua.jpg',
    price: 9.95,
    wine_type: 'Red Wine',
    grapes: 'Carménère',
    region: 'Chile / Aconcagua Valley',
    wine_style: 'Chilean Carménère',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/errazuriz-carmenere-max-reserva/',
    name: 'Errazuriz Carmenere Max Reserva',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/errazuriz-max-reserva-carmenere-2016-aconcagua-val.jpg',
    price: 15.95,
    wine_type: 'Red Wine',
    grapes: 'Carménère',
    region: 'Chile / Aconcagua Valley',
    wine_style: 'Chilean Carménère',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/marchesi-di-barolo-barolo-tradizione/',
    name: 'Marchesi di Barolo Barolo Tradizione',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/marchesi_di_barolo_barolo_tradizione_lieblings-weine.jpg',
    price: 42.95,
    wine_type: 'Red Wine',
    grapes: 'Nebbiolo',
    region: 'Italy / Barolo',
    wine_style: 'Italian Barolo',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/barolo-cannubi/',
    name: 'Marchesi di Barolo Cannubi',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/barolo-cannubi-valletta-1993-marchesi-di-barolo.jpg',
    price: 55.5,
    wine_type: 'Red Wine',
    grapes: 'Nebbiolo',
    region: 'Italy / Barolo',
    wine_style: 'Italian Barolo',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/marchesi-di-barolo-cannubi-kopie/',
    name: "Marchesi di Barolo Barbera d'Alba Peiragal",
    image: 'https://dezwartdranken.nl/wp-content/uploads/2020/03/unnamed.jpg',
    price: 27.5,
    wine_type: 'Red Wine',
    grapes: 'Barbera',
    region: "Italy / Barbera d'Alba",
    wine_style: 'Italian Barbera',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/vicente-gandia-nebla-tempranillo/',
    name: 'Vicente Gandia Nebla Tempranillo',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/nebla_tinto.jpg',
    price: 11.75,
    wine_type: 'Red Wine',
    grapes: 'Tempranillo',
    region: 'Spain / Castilla y León / Ribera del Duero',
    wine_style: 'Spanish Ribera Del Duero Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/vicente-gandia-raiza-reserva-rioja/',
    name: 'Vicente Gandia Raiza Gran Reserva Rioja',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/DSC25155dc17dc23c848.jpg',
    price: 20.75,
    wine_type: 'Red Wine',
    grapes: 'Tempranillo',
    region: 'Spain / Rioja',
    wine_style: 'Spanish Rioja Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/portillo-pinot-noir/',
    name: 'Portillo Pinot Noir',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Portillo-Pinot-Noir.jpg',
    price: 8.95,
    wine_type: 'Red Wine',
    grapes: 'Pinot Noir',
    region: 'Argentina / Uco Valley',
    wine_style: 'Argentinian Pinot Noir',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/errazuriz-pinot-noir-estate/',
    name: 'Errazuriz Pinot Noir Estate',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/estate-errazuriz-pinot-noir.jpg',
    price: 9.95,
    wine_type: 'Red Wine',
    grapes: 'Pinot Noir',
    region: 'Chile / Aconcagua Valley',
    wine_style: 'Chilean Pinot Noir',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/salentein-barrel-selection-pinot-noir/',
    name: 'Salentein Barrel Selection Pinot Noir',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Salentein-Barrel-Selection-Pinot-Noir.jpg',
    price: 14.95,
    wine_type: 'Red Wine',
    grapes: 'Pinot Noir',
    region: 'Argentina / Uco Valley',
    wine_style: 'Argentinian Pinot Noir',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/laurent-miquel-les-auzines-rouge/',
    name: 'Laurent Miquel Les Auzines Rouge',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/06/0afbeelding0466775_7.png',
    price: 11.95,
    wine_type: 'Red Wine',
    grapes: 'Grenache, Carignan, Cinsault',
    region: 'France / Languedoc',
    wine_style: 'Languedoc-Roussillon Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/poggio-le-volpi-roma-doc-rosato/',
    name: 'Poggio Le Volpi Roma DOC Rosato',
    image: 'https://dezwartdranken.nl/wp-content/uploads/2020/08/roma-rose.jpg',
    price: 17.5,
    wine_type: 'Rose Wine',
    grapes: 'Shiraz/Syrah, Montepulciano',
    region: 'Italy / Lazio',
    wine_style: '',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/bernardus-pinot-noir/',
    name: 'Bernardus Pinot Noir',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/a38b52082bca58928bacddedb31841c368177f2b_744818220112.jpeg',
    price: 30.5,
    wine_type: 'Red Wine',
    grapes: 'Pinot Noir',
    region: 'United States / Monterey County',
    wine_style: 'Californian Pinot Noir',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/doos-salentein-barrel-selection-pinot-noir/',
    name: 'Doos Salentein Barrel Selection Pinot Noir',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Salentein-Barrel-Selection-Pinot-Noir.jpg',
    price: 89.7,
    wine_type: 'Red Wine',
    grapes: 'Pinot Noir',
    region: 'United States / Russian River Valley',
    wine_style: 'Californian Pinot Noir',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/farina-valpolicella-classico-superiore/',
    name: 'Farina Valpolicella Classico Superiore',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Farina-valpolicella-van-dort-wijnspecialist.jpg',
    price: 12.5,
    wine_type: 'Red Wine',
    grapes: 'Dindarella, Rondinella, Molinara, Corvinone, Corvina',
    region: 'Italy / Valpolicella Classico',
    wine_style: 'Italian Valpolicella Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/montgravet-syrah/',
    name: 'Montgravet Syrah',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/montgravet-syrah-800x800-1.png',
    price: 7.95,
    wine_type: 'Red Wine',
    grapes: 'Shiraz/Syrah',
    region: "France / Pays d'Oc",
    wine_style: 'Languedoc-Roussillon Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/ellermann-spiegel-spatburgunder-trocken/',
    name: 'Ellermann-Spiegel Spätburgunder Trocken',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/0afbeelding50220617_2.jpg',
    price: 12.9,
    wine_type: 'Red Wine',
    grapes: 'Spätburgunder',
    region: 'Germany / Pfalz',
    wine_style: 'German Spätburgunder',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/wild-rock-pinot-noir/',
    name: 'Wild Rock Pinot Noir',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/wild-rock-pinot-noir-2016-5cb.jpg',
    price: 20.5,
    wine_type: 'Red Wine',
    grapes: 'Pinot Noir',
    region: 'New Zealand / South Island / Marlborough',
    wine_style: 'New Zealand Pinot Noir',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/nautilus-pinot-noir/',
    name: 'Nautilus Pinot Noir',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Nautilus-Estate-Southern-Valleys-Pinot-Noir.png',
    price: 24.95,
    wine_type: 'Red Wine',
    grapes: 'Pinot Noir',
    region: 'New Zealand / South Island / Marlborough',
    wine_style: 'New Zealand Pinot Noir',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/louis-jadot-couvent-des-jacobins-pinot-noir/',
    name: 'Louis Jadot Couvent des Jacobins Pinot Noir',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Louis-Jadot-Couvent-des-Jacobins-Pinot-Noir.jpg',
    price: 19.95,
    wine_type: 'Red Wine',
    grapes: 'Pinot Noir',
    region: 'France / Bourgogne',
    wine_style: 'Burgundy Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/wijn-proeverij-bourgogne/',
    name: 'Wijn Proeverij Bourgogne',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/10/Bourgogne-1-rotated.jpg',
    price: 80,
    wine_type: '',
    grapes: '',
    region: 'Burgundy',
    wine_style: '',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/epicuro-montepulciano-dabruzzo/',
    name: 'Epicuro Montepulciano d’Abruzzo',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Epicuro-Montepulciano-1.jpg',
    price: 7.45,
    wine_type: 'Red Wine',
    grapes: 'Montepulciano',
    region: "Italy / Montepulciano d'Abruzzo",
    wine_style: "Italian Montepulciano d'Abruzzo",
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/vigne-de-lenfant-jesus-2012/',
    name: "Vigne de l'Enfant Jésus 2012",
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/20178019918-ms-scaled.jpg',
    price: 119.95,
    wine_type: 'Red Wine',
    grapes: 'Pinot Noir',
    region: "France / Beaune 1er Cru 'Les Grèves'",
    wine_style: 'Burgundy Côte de Beaune Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/barone-cornacchia-casanova-pecorino/',
    name: 'Barone Cornacchia Casanova Pecorino',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/10/Pecorino_baronecornacchia.jpg',
    price: 11.95,
    wine_type: 'White Wine',
    grapes: 'Pecorino',
    region: 'Italy / Abruzzo / Controguerra',
    wine_style: 'Southern Italy White',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/grands-fers-fleurie/',
    name: 'Grands Fers Fleurie',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/10/Grands-Fers-Fleurie.jpg',
    price: 17.95,
    wine_type: 'Red Wine',
    grapes: 'Gamay',
    region: 'France / Fleurie',
    wine_style: 'Beaujolais Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/carnivor-zinfandel/',
    name: 'Carnivor Zinfandel',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/carnivor-zinfandel-1500672.png',
    price: 14.95,
    wine_type: 'Red Wine',
    grapes: 'Zinfandel',
    region: 'United States / California',
    wine_style: 'Californian Zinfandel',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/megazin-zinfandel/',
    name: 'Megazin Zinfandel',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/megazin-800x800-1.jpg',
    price: 14.5,
    wine_type: 'Red Wine',
    grapes: 'Zinfandel',
    region: 'United States / California',
    wine_style: 'Californian Zinfandel',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/kendall-jackson-vintners-reserve-zinfandel/',
    name: "Kendall-Jackson Vintner's Reserve Zinfandel",
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Kendall-Jackson-Zinfandel-Vintners-Reserve.jpg',
    price: 19.95,
    wine_type: 'Red Wine',
    grapes: 'Zinfandel',
    region: 'United States / Mendocino County',
    wine_style: 'Californian Zinfandel',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/epicuro-negroamaro-cabernet-sauvignon/',
    name: 'Epicuro Negroamaro - Cabernet Sauvignon',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/epicuro-negroamaro-cab-sauvignon-1.jpg',
    price: 7.95,
    wine_type: 'Red Wine',
    grapes: 'Cabernet Sauvignon, Negroamaro',
    region: 'Italy / Puglia',
    wine_style: 'Southern Italy Red',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/tenuta-santantonio-amarone-della-valpolicella-selezione/',
    name: "Tenuta Sant'Antonio Amarone della Valpolicella Selezione",
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/2013-Amarone-della-Valpolicella-Castagnedi-DOCG-Tenuta-Sant-Antonio-italianwinetrading.jpg',
    price: 39.95,
    wine_type: 'Red Wine',
    grapes:
      'Croatina, Montepulciano, Oseleta, Cabernet Sauvignon, Corvina, Rondinella',
    region: 'Italy / Amarone della Valpolicella',
    wine_style: 'Italian Amarone',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/feudo-montoni-nero-davola-lagnusa-bio/',
    name: 'Feudo Montoni Nero d’Avola Lagnusa Bio',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/feudo_montoni_vigna_lagnusa_nero_d_avola_sicilia_doc-300x300-1.png',
    price: 14.95,
    wine_type: 'Red Wine',
    grapes: "Nero d'Avola",
    region: 'Itália / Sicilia',
    wine_style: 'Tinto do sul italiano',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/degras-reserva-carmenere/',
    name: 'Degras Reserva Carmenere',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/de_gras-reserva-carmen_re.jpg',
    price: 9.95,
    wine_type: 'Red Wine',
    grapes: 'Carménère',
    region: 'Chile / Central Valley',
    wine_style: 'Chilean Carménère',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/simonsig-cabernet-sauvignon-shiraz/',
    name: 'Simonsig Cabernet Sauvignon-Shiraz',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/SIMONSIG-CABERNET-SAUVIGNON-SHIRAZ-750ML-800x800-1.jpg',
    price: 8.5,
    wine_type: 'Red Wine',
    grapes: 'Shiraz/Syrah, Cabernet Sauvignon',
    region: 'South Africa / Stellenbosch',
    wine_style: 'South African Cabernet - Syrah',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/guillaume-virginie-philip-mip-classic-rose/',
    name: 'Guillaume & Virginie Philip MIP Classic Rosé',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/2019-mip-classic-rose-guillaume-virginie-philip.jpg',
    price: 14.95,
    wine_type: 'Rose Wine',
    grapes: 'Shiraz/Syrah, Cinsault, Garnacha',
    region: 'France / Provence / Côtes de Provence',
    wine_style: 'Provence Rosé',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/oxford-landing-estates-shiraz/',
    name: 'Oxford Landing Estates Shiraz',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Oxford-Landing-Estates-Shiraz.png',
    price: 7.95,
    wine_type: 'Red Wine',
    grapes: 'Shiraz/Syrah',
    region: 'Australia / South Australia',
    wine_style: 'Shiraz australiano',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/yalumba-organic-shiraz/',
    name: 'Yalumba Organic Shiraz',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Yalumba-Organic-Shiraz.png',
    price: 11.95,
    wine_type: 'Red Wine',
    grapes: 'Shiraz/Syrah',
    region: 'Australia / South Australia',
    wine_style: 'Australian Shiraz',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/carnivor-cabernet-sauvignon/',
    name: 'Carnivor Cabernet Sauvignon',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/images_-_2019-08-03t111547.712.jpeg',
    price: 14.95,
    wine_type: 'Red Wine',
    grapes: 'Cabernet Sauvignon',
    region: 'United States / California',
    wine_style: 'Californian Cabernet Sauvignon',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/beringer-classic-cabernet-sauvignon/',
    name: 'Beringer Classic Cabernet Sauvignon',
    image: 'https://dezwartdranken.nl/wp-content/uploads/2020/03/image-5.jpg',
    price: 10.95,
    wine_type: 'Red Wine',
    grapes: 'Cabernet Sauvignon',
    region: 'Estados Unidos / Califórnia',
    wine_style: 'Cabernet Sauvignon Californiano',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/delaire-graff-estate-shiraz/',
    name: 'Delaire Graff Estate Shiraz',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Delaire-Shiraz-2016-NV-scaled.jpg',
    price: 15.95,
    wine_type: 'Red Wine',
    grapes: 'Shiraz/Syrah',
    region: 'South Africa / Stellenbosch',
    wine_style: 'South African Syrah',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/yalumba-the-y-series-shiraz-viognier/',
    name: 'Yalumba The Y Series Shiraz - Viognier',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/yalumba-the-y-series-shiraz-viognier-2018-south-au.jpg',
    price: 9.95,
    wine_type: 'Red Wine',
    grapes: 'Viognier',
    region: 'Australia / South Australia',
    wine_style: 'Australian Syrah - Viognier',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/chateau-batailley-pauillac-2014/',
    name: 'Chateau Batailley Pauillac 2014',
    image: 'https://dezwartdranken.nl/wp-content/uploads/2020/03/cr280.jpg',
    price: 54.75,
    wine_type: 'Red Wine',
    grapes:
      '70% Cabernet Sauvignon, 25% Merlot, 3% Cabernet Franc, 2% Petit Verdot',
    region: 'France / Bordeaux / Médoc / Pauillac',
    wine_style: 'Bordeaux Pauillac',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/vicente-gandia-nebla-verdejo/',
    name: 'Vicente Gandia Nebla Verdejo',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/nebla_verdjo.jpg',
    price: 8.5,
    wine_type: 'White Wine',
    grapes: 'Verdejo',
    region: 'Spain / Castilla y León / Rueda',
    wine_style: 'Spanish Verdejo',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/twin-islands-sauvignon-blanc/',
    name: 'Twin Islands Sauvignon Blanc',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/twin-islands-sauvignon-blanc-2018-marlborough-nieu.jpg',
    price: 11.95,
    wine_type: 'White Wine',
    grapes: 'Sauvignon Blanc',
    region: 'New Zealand / Marlborough',
    wine_style: 'New Zealand Sauvignon Blanc',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/xr-sauvignon-blanc/',
    name: 'XR Sauvignon Blanc',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/sauvignon_blanc_xr_xavier_roger.jpg',
    price: 6.95,
    wine_type: 'White Wine',
    grapes: 'Sauvignon Blanc',
    region: 'France / Côtes de Gascogne',
    wine_style: 'France / Vin de France',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/boschendal-1685-chenin-blanc/',
    name: 'Boschendal 1685 Chenin Blanc',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Boschendal-1685-Chenin-Blanc.jpg',
    price: 14.95,
    wine_type: 'White Wine',
    grapes: 'Chenin Blanc',
    region: 'South Africa / Western Cape',
    wine_style: 'South African Chenin Blanc',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/joseph-mellot-menetou-salon-blanc-clos-du-pressoir/',
    name: 'Joseph Mellot Menetou Salon Blanc Clos du Pressoir',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/clos-du-pressoir-2018-joseph-mellot.png',
    price: 23.5,
    wine_type: 'White Wine',
    grapes: 'Sauvignon Blanc',
    region: 'France / Loire',
    wine_style: 'Upper Loire White',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/joseph-mellot-pouilly-fume-les-troncsec/',
    name: 'Joseph Mellot Pouilly Fumé Les Troncsec',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/pouilly-fume-le-troncsec-075l-2_1.jpg',
    price: 26.95,
    wine_type: 'White Wine',
    grapes: 'Sauvignon Blanc',
    region: 'France / Pouilly-Fumé',
    wine_style: 'Upper Loire White',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/joseph-mellot-sancerre-la-chatellenie/',
    name: 'Joseph Mellot Sancerre La Chatellenie',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/sancerre-la-graveliere-075l-2-5daeb737d2e1c.jpg',
    price: 19.95,
    wine_type: 'White Wine',
    grapes: 'Sauvignon Blanc',
    region: 'France / Sancerre',
    wine_style: 'Upper Loire White',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/silver-moki-sauvignon-blanc/',
    name: 'Silver Moki Sauvignon Blanc',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/04/silver_moki_sauvignon_blanc.jpg',
    price: 9.95,
    wine_type: 'White Wine',
    grapes: 'Sauvignon Blanc',
    region: 'New Zealand / Marlborough',
    wine_style: 'New Zealand Sauvignon Blanc',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/haha-sauvignon-blanc/',
    name: 'Hãhã Sauvignon Blanc',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/04/Haha-450x450-1.jpg',
    price: 14.5,
    wine_type: 'White Wine',
    grapes: 'Sauvignon Blanc',
    region: 'New Zealand / Marlborough',
    wine_style: 'New Zealand Sauvignon Blanc',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/simonsig-chenin-blanc-vegan/',
    name: 'Simonsig Chenin Blanc ( Vegan )',
    image: 'https://dezwartdranken.nl/wp-content/uploads/2020/03/12847_AS.png',
    price: 8.25,
    wine_type: 'White Wine',
    grapes: 'Chenin Blanc',
    region: 'South Africa / Stellenbosch',
    wine_style: 'South African Chenin Blanc',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/wild-rock-sauvignon-blanc/',
    name: 'Wild Rock Sauvignon Blanc',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/wildrock_71eee96c-85c6-4ec7-aa0a-079fa221f1d7_800x.jpg',
    price: 12.75,
    wine_type: 'White Wine',
    grapes: 'Riesling, Sauvignon Blanc, Viognier',
    region: 'New Zealand / Marlborough',
    wine_style: 'New Zealand Sauvignon Blanc',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/errazuriz-chardonnay-max-reserva/',
    name: 'Errazuriz Chardonnay Max Reserva',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/errazurizchar.png',
    price: 15.95,
    wine_type: 'White Wine',
    grapes: 'Chardonnay',
    region: 'Chile / Aconcagua Valley',
    wine_style: 'Chilean Chardonnay',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/errazuriz-chardonnay-estate/',
    name: 'Errazuriz Chardonnay Estate',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/errazuriz-estate-series-chardonnay-2018-casablanca.jpg',
    price: 9.95,
    wine_type: 'White Wine',
    grapes: 'Chardonnay',
    region: 'Chile / Casablanca Valley',
    wine_style: 'Chilean Chardonnay',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/epicuro-chardonnay-fiano/',
    name: 'Epicuro Chardonnay - Fiano',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Epicuro-Chardonnay-Fiano.png',
    price: 7.95,
    wine_type: 'White Wine',
    grapes: 'Chardonnay',
    region: 'Italy / Puglia',
    wine_style: 'Southern Italy White',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/abbotts-delaunay-sauvignon-blanc/',
    name: 'Abbotts & Delaunay Sauvignon Blanc',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/2791_abbotts_delaunay_sauvignon_blanc_voor-1.jpg',
    price: 10.5,
    wine_type: 'White Wine',
    grapes: 'Viognier',
    region: "France / Pays d'Oc",
    wine_style: 'Languedoc-Roussillon Viognier',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/yalumba-the-y-series-viognier/',
    name: 'Yalumba The Y Series Viognier',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/yalumbaviognier.jpg',
    price: 9.95,
    wine_type: 'White Wine',
    grapes: 'Viognier',
    region: 'Australia / South Australia',
    wine_style: 'Australian Viognier',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/degras-reserva-chardonnay/',
    name: 'Degras Reserva Chardonnay',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/montgras-degras-reserva-chardonnay-1459649-s341_p.jpg',
    price: 9.95,
    wine_type: 'White Wine',
    grapes: 'Chardonnay',
    region: 'Chile / Colchagua Valley',
    wine_style: 'Chilean Chardonnay',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/degras-estate-chardonnay/',
    name: 'Degras Estate Chardonnay',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/de_gras-estate-chardonnay.jpg',
    price: 6.95,
    wine_type: 'White Wine',
    grapes: 'Chardonnay',
    region: 'Chile / Central Valley',
    wine_style: 'Chilean Chardonnay',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/doos-salentein-barrel-selection-chardonnay/',
    name: 'Doos Salentein Barrel Selection Chardonnay',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/salentein-barrel-chardonnay.jpg',
    price: 89.7,
    wine_type: 'White Wine',
    grapes: 'Chardonnay',
    region: 'Chile / Central Valley',
    wine_style: 'Chilean Chardonnay',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/m-chapoutier-belleruche-cotes-du-rhone-blanc/',
    name: 'M. Chapoutier “Belleruche” Côtes-du-Rhône Blanc',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/belleruche-cotes-du-rhone-white-075l-2_1.jpg',
    price: 9.95,
    wine_type: 'White Wine',
    grapes: 'Grenache Blanc',
    region: 'France / Côtes-du-Rhône',
    wine_style: 'Southern Rhône White',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/m-chapoutier-cotes-du-rhone-belleruche-rouge/',
    name: 'M. Chapoutier Côtes-du-Rhône “Belleruche” Rouge',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/belleruche_1.jpg',
    price: 9.95,
    wine_type: 'White Wine',
    grapes: 'Grenache Blanc',
    region: 'França / Côtes-du-Rhône',
    wine_style: 'Sul do Rhône branco',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/lenotti-bianco-del-veneto-colle-dei-tigli/',
    name: 'Lenotti Bianco del Veneto Colle dei Tigli',
    image: 'https://dezwartdranken.nl/wp-content/uploads/2020/03/unnamed-1.jpg',
    price: 8.5,
    wine_type: 'White Wine',
    grapes: 'Garganega, Viognier, Cortese',
    region: 'Itália / Veneto',
    wine_style: 'Branco do norte italiano',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/boschendal-jean-garde-unoaked-chardonnay/',
    name: 'Boschendal Jean Garde Unoaked Chardonnay',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Boschendal-Unoaked-Chardonnay.png',
    price: 9.5,
    wine_type: 'White Wine',
    grapes: 'Chardonnay',
    region: 'South Africa / Western Cape',
    wine_style: 'South African Chardonnay',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/radford-dale-chardonnay/',
    name: 'Radford Dale Chardonnay',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Screenshot-2020-03-19-at-09.07.38.png',
    price: 25.5,
    wine_type: 'White Wine',
    grapes: 'Chardonnay',
    region: 'South Africa / Stellenbosch',
    wine_style: 'South African Chardonnay',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/boschendal-1685-chardonnay/',
    name: 'Boschendal 1685 Chardonnay',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/1685-chardonnay-800x800-1.jpg',
    price: 14.95,
    wine_type: 'White Wine',
    grapes: 'Chardonnay',
    region: 'South Africa / Western Cape',
    wine_style: 'South African Chardonnay',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/monte-llano-viura/',
    name: 'Monte Llano Viura',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/monte-llano-viura-2018-doc-rioja-spanje.jpg',
    price: 7.75,
    wine_type: 'White Wine',
    grapes: 'Viura',
    region: 'Spain / Rioja',
    wine_style: 'Spanish Rioja White',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/epicuro-pinot-grigio/',
    name: 'Epicuro Pinot Grigio',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Epicuro-Pinot-Grigio.jpg',
    price: 7.95,
    wine_type: 'White Wine',
    grapes: 'Pinot Grigio',
    region: 'Italy / Terre Siciliane',
    wine_style: 'Southern Italy White',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/salentein-barrel-selection-chardonnay/',
    name: 'Salentein Barrel Selection Chardonnay',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/salentein-barrel-chardonnay.jpg',
    price: 14.95,
    wine_type: 'White Wine',
    grapes: 'Chardonnay',
    region: 'Argentina / Uco Valley',
    wine_style: 'Argentinian Chardonnay',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/feudo-montoni-catarratto-del-masso-bio/',
    name: 'Feudo Montoni Catarratto del Masso Bio',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/vignadelmasso.jpg',
    price: 14.95,
    wine_type: 'White Wine',
    grapes: 'Catarratto Bianco',
    region: 'Itália / Sicilia',
    wine_style: 'Branco do sul italiano',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/feudo-montoni-grillo-della-timpa-bio/',
    name: 'Feudo Montoni Grillo della Timpa Bio',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/4okF0WknRju0nxUBBbhN2w_pb_600x600.png',
    price: 15.5,
    wine_type: 'White Wine',
    grapes: 'Grillo',
    region: 'Italy / Sicilia',
    wine_style: 'Southern Italy White',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/pasqua-passimento-bianco/',
    name: 'Pasqua Passimento Bianco',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/passimento_bianco.jpg',
    price: 11.75,
    wine_type: 'White Wine',
    grapes: 'Garganega',
    region: 'Italy / Veneto',
    wine_style: 'Northern Italy White',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/beringer-classic-chardonnay/',
    name: 'Beringer Classic Chardonnay',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/beringer-classic-chardonnay.jpg',
    price: 10.95,
    wine_type: 'White Wine',
    grapes: 'Chardonnay',
    region: 'United States / California',
    wine_style: 'Californian Chardonnay',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/bernardus-chardonnay/',
    name: 'Bernardus Chardonnay',
    image: 'https://dezwartdranken.nl/wp-content/uploads/2020/03/bernard.jpg',
    price: 29.95,
    wine_type: 'White Wine',
    grapes: 'Chardonnay',
    region: 'United States / Monterey County',
    wine_style: 'Californian Chardonnay',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/kendall-jackson-vintners-reserve-chardonnay/',
    name: "Kendall-Jackson Vintner's Reserve Chardonnay",
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/kendall-jackson-vintners-reserve-chardonnay-2017-c.jpg',
    price: 19.95,
    wine_type: 'White Wine',
    grapes: 'Chardonnay',
    region: 'United States / California',
    wine_style: 'Californian Chardonnay',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/farina-pinot-grigio-del-veneto/',
    name: 'Farina Pinot Grigio del Veneto',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/farina-pinot-grigio-delle-venezie-2019-doc-italie.jpg',
    price: 7.95,
    wine_type: 'White Wine',
    grapes: 'Pinot Grigio',
    region: 'Italy / Veneto',
    wine_style: 'Northern Italy Pinot Grigio',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/laurent-miquel-les-auzines-albarino-kopie/',
    name: 'Laurent Miquel Les Auzines Albariño',
    image: 'https://dezwartdranken.nl/wp-content/uploads/2020/06/418399.jpg',
    price: 11.95,
    wine_type: 'White Wine',
    grapes: 'Albariño',
    region: 'France / Languedoc-Roussillon',
    wine_style: 'Languedoc-Roussillon White',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/masi-pinot-grigio/',
    name: 'Masi Pinot Grigio',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/06/pinot-modello-masi-scaled.jpg',
    price: 9.95,
    wine_type: 'White Wine',
    grapes: 'Pinot Grigio',
    region: 'Italy / Veneto',
    wine_style: 'Northern Italy Pinot Grigio',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/manoir-grignon-chardonnay/',
    name: 'Manoir Grignon Chardonnay',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/manoir_grignon_chardonnay15.jpg',
    price: 7.95,
    wine_type: 'White Wine',
    grapes: 'Chardonnay',
    region: "France / Pays d'Oc",
    wine_style: 'Languedoc-Roussillon White',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/ellermann-spiegel-grauburgunder-trocken/',
    name: 'Ellermann-Spiegel Grauburgunder Trocken',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/ellermann-spiegel-grauburgunder-trocken-1553160-s668_p.png',
    price: 12.9,
    wine_type: 'White Wine',
    grapes: 'Grauburgunder',
    region: 'Germany / Pfalz',
    wine_style: 'German Grauburgunder',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/laurent-miquel-pere-et-fils-chardonnay-viognier/',
    name: 'Laurent Miquel Père et Fils Chardonnay - Viognier',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/LM-Pere-et-Fils-Chardonnay-Viognier.jpg',
    price: 7.95,
    wine_type: 'White Wine',
    grapes: 'Viognier',
    region: 'France / Languedoc-Roussillon',
    wine_style: 'Languedoc-Roussillon White',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/laurent-miquel-pere-et-fils-sauvignon-blanc/',
    name: 'Laurent Miquel Père et Fils Sauvignon Blanc',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Pere-et-fils-sauvignon-blanc.jpg',
    price: 7.95,
    wine_type: 'White Wine',
    grapes: 'Viognier, Chardonnay',
    region: 'France / Languedoc-Roussillon',
    wine_style: 'Languedoc-Roussillon branco',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/portillo-chardonnay/',
    name: 'Portillo Chardonnay',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/portillo_chardonnay_nw_.jpg',
    price: 8.95,
    wine_type: 'White Wine',
    grapes: 'Chardonnay',
    region: 'Argentina / Uco Valley',
    wine_style: 'Argentinian Chardonnay',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/ramon-bilbao-edicion-limitada-lias-verdejo/',
    name: 'Ramon Bilbao Edición Limitada Lías Verdejo',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Ramón-Bilbao-Edición-Limitada-Lías-Verdejo.png',
    price: 16.5,
    wine_type: 'White Wine',
    grapes: 'Verdejo',
    region: 'Spain / Rueda',
    wine_style: 'Spanish Verdejo',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/ellermann-spiegel-weissburgunder-trocken/',
    name: 'Ellermann-Spiegel Weissburgunder Trocken',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/ellermann-spiegel-weissburgunder-trocken-qba-pfalz-2017.png',
    price: 12.9,
    wine_type: 'White Wine',
    grapes: 'Weissburgunder',
    region: 'Germany / Pfalz',
    wine_style: 'German Pinot Blanc',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/yalumba-the-y-series-chardonnay/',
    name: 'Yalumba The Y Series Chardonnay',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Yalumba-Chardonnay-Y-Series.png',
    price: 9.95,
    wine_type: 'White Wine',
    grapes: 'Chardonnay',
    region: 'Australia / South Australia',
    wine_style: 'Australian Chardonnay',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/oxford-landing-estates-chardonnay/',
    name: 'Oxford Landing Estates Chardonnay',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Oxford-Landing-Chardonnay.jpg',
    price: 7.95,
    wine_type: 'White Wine',
    grapes: 'Chardonnay',
    region: 'Austrália / South Australia',
    wine_style: 'Chardonnay australiano',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/farina-chardonnay-del-veneto/',
    name: 'Farina Chardonnay del Veneto',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Farina-Chardonnay.png',
    price: 7.95,
    wine_type: 'White Wine',
    grapes: 'Chardonnay',
    region: 'Italy / Veneto',
    wine_style: 'Branco do norte italiano',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/boschendal-1685-sauvignon-blanc-grande-cuvee/',
    name: 'Boschendal 1685 Sauvignon Blanc Grande Cuvée',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/boschendal-1685-grande-cuv_e-sauvignon-blanc-2016_1.jpg',
    price: 14.95,
    wine_type: 'White Wine',
    grapes: 'Sauvignon Blanc, Sémillon',
    region: 'South Africa / Western Cape / Coastal Region',
    wine_style: 'South African Sauvignon Blanc',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/delaire-graff-estate-sauvignon-blanc/',
    name: 'Delaire Graff Estate Sauvignon Blanc',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Delaire-Graff-Sauvignon-Blanc-2014-SOLD-OUT.jpg',
    price: 15.95,
    wine_type: 'White Wine',
    grapes: 'Sauvignon Blanc',
    region: 'South Africa / Western Cape',
    wine_style: 'South African Sauvignon Blanc',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/ellermann-spiegel-chardonnay-goldkapsel/',
    name: "Ellermann-Spiegel Chardonnay 'Goldkapsel'",
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/124914_1-scaled.jpg',
    price: 15.95,
    wine_type: 'White Wine',
    grapes: 'Chardonnay',
    region: 'Germany / Pfalz',
    wine_style: 'German Chardonnay',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/epicuro-vermentino/',
    name: 'Epicuro Vermentino',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/Epicuro-Vermentino.png',
    price: 7.95,
    wine_type: 'White Wine',
    grapes: 'Vermentino',
    region: 'Italy / Terre Siciliane',
    wine_style: 'Southern Italy White',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/domaine-du-colombier-chablis-1er-cru-fourchaume/',
    name: 'Domaine du Colombier Chablis 1er Cru Fourchaume',
    image: 'https://dezwartdranken.nl/wp-content/uploads/2020/03/cn41b.jpg',
    price: 29.95,
    wine_type: 'White Wine',
    grapes: 'Chardonnay',
    region: "France / Chablis 1er Cru 'Fourchaume'",
    wine_style: 'Burgundy Chablis',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/doos-salentein-sauvignon-blanc/',
    name: 'Doos Salentein Sauvignon Blanc',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/image_2549.jpg',
    price: 89.7,
    wine_type: 'White Wine',
    grapes: 'Sauvignon Blanc',
    region: 'Argentina / Mendoza / Uco Valley',
    wine_style: 'Argentinian Sauvignon Blanc',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/errazuriz-sauvignon-blanc-estate/',
    name: 'Errazuriz Sauvignon Blanc Estate',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/snapshotimagehandler_580174264.jpeg',
    price: 9.95,
    wine_type: 'White Wine',
    grapes: 'Sauvignon Blanc',
    region: 'Chile / Aconcagua Valley',
    wine_style: 'Chilean Sauvignon Blanc',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1:
      'https://dezwartdranken.nl/product/oxford-landing-estates-sauvignon-blanc/',
    name: 'Oxford Landing Estates Sauvignon Blanc',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/snapshotimagehandler_2083990128.jpeg',
    price: 7.95,
    wine_type: 'White Wine',
    grapes: 'Sauvignon Blanc',
    region: 'Australia / South Australia',
    wine_style: 'Australian Sauvignon Blanc',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/portillo-sauvignon-blanc/',
    name: 'Portillo Sauvignon Blanc',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/portillo-sauvignon-blanc-1.jpg',
    price: 8.95,
    wine_type: 'White Wine',
    grapes: 'Sauvignon Blanc',
    region: 'Argentina / Mendoza / Uco Valley',
    wine_style: 'Argentinian Sauvignon Blanc',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/salentein-sauvignon-blanc/',
    name: 'Salentein Sauvignon Blanc',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/image_2549.jpg',
    price: 14.95,
    wine_type: 'White Wine',
    grapes: 'Sauvignon Blanc',
    region: 'Argentina / Uco Valley',
    wine_style: 'Argentinian Sauvignon Blanc',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/poggio-le-volpi-roma-bianco/',
    name: 'Poggio Le Volpi Roma Bianco',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/08/roma-bianco.jpg',
    price: 17.5,
    wine_type: 'White Wine',
    grapes: 'Malvasia',
    region: 'Italy / Lazio',
    wine_style: 'Central Italy White',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/degras-estate-sauvignon-blanc/',
    name: 'Degras Estate Sauvignon Blanc',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/de_gras_estate_sauvignon_blanc.jpg',
    price: 6.95,
    wine_type: 'White Wine',
    grapes: 'Sauvignon Blanc',
    region: 'Chile / Colchagua Valley',
    wine_style: 'Sauvignon Blanc chileno',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
  {
    url_1: 'https://dezwartdranken.nl/product/nautilus-sauvignon-blanc/',
    name: 'Nautilus Sauvignon Blanc',
    image:
      'https://dezwartdranken.nl/wp-content/uploads/2020/03/nautilus-estate-nautilus-estate-sauvignon-blanc-ma.jpg',
    price: 16.5,
    wine_type: 'White Wine',
    grapes: 'Sauvignon Blanc',
    region: 'New Zealand / Marlborough',
    wine_style: 'New Zealand Sauvignon Blanc',
    Body: '',
    Acidity: '',
    Tannins: '',
    Sweetness: '',
  },
]
